import { GlassPanel } from "@/components/glass-panel";

export default function TermsPage() {
  return (
    <div className="min-h-dvh px-4 pb-20 pt-16 md:px-8">
      <div className="mx-auto max-w-3xl space-y-6">
        <GlassPanel className="p-6 md:p-8">
          <h1 className="text-2xl font-semibold text-gray-900 md:text-3xl dark:text-white">
            Terms of Service
          </h1>
          <p className="mt-2 text-sm text-gray-600 dark:text-white/60">
            These Terms of Service govern your access to and use of Circle, the
            AI council platform. By using Circle, you agree to these terms.
          </p>
        </GlassPanel>

        <GlassPanel className="space-y-4 p-6 text-sm text-gray-800 md:p-7 dark:text-white/80">
          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white">
              1. Use of the service
            </h2>
            <p className="mt-1 text-gray-700 dark:text-white/70">
              Circle is provided for informational and exploratory purposes. You
              agree not to misuse the service, attempt to interfere with its
              operation, or use it in violation of applicable laws or
              regulations.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white">
              2. Accounts and security
            </h2>
            <p className="mt-1 text-gray-700 dark:text-white/70">
              You are responsible for maintaining the confidentiality of your
              account and for all activity that occurs under it. Notify us
              promptly of any unauthorized use or suspected breach of security.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white">
              3. Content and ownership
            </h2>
            <p className="mt-1 text-gray-700 dark:text-white/70">
              You retain ownership of the ideas and content you submit to
              Circle. By using the service, you grant us a limited license to
              process, store, and analyze that content for the purpose of
              operating and improving the platform, in accordance with the
              Privacy Policy and your settings.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white">
              4. No professional advice
            </h2>
            <p className="mt-1 text-gray-700 dark:text-white/70">
              Outputs from the AI council are generated by machine learning
              models and should not be treated as professional advice (legal,
              financial, medical, or otherwise). You are solely responsible for
              how you use the information provided by Circle.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white">
              5. Service changes and termination
            </h2>
            <p className="mt-1 text-gray-700 dark:text-white/70">
              We may modify, suspend, or discontinue parts of the service at any
              time. We may terminate or suspend your access if you violate these
              terms or if we reasonably believe it is necessary to protect the
              service or other users.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white">
              6. Disclaimers and limitation of liability
            </h2>
            <p className="mt-1 text-gray-700 dark:text-white/70">
              Circle is provided &quot;as is&quot; without warranties of any kind,
              express or implied. To the maximum extent permitted by law, we
              shall not be liable for any indirect, incidental, or consequential
              damages arising from your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 dark:text-white">
              7. Governing law
            </h2>
            <p className="mt-1 text-gray-700 dark:text-white/70">
              These terms are governed by the laws of the applicable
              jurisdiction in which Circle is operated. Any disputes will be
              resolved exclusively in the courts of that jurisdiction, unless
              otherwise required by law.
            </p>
          </section>
        </GlassPanel>
      </div>
    </div>
  );
}

